[data]
x = "x_location" # Name of the x column in the input data. Default: "x"
y = "y_location" # Name of the y column in the input data. Default: "y"
z = "z_location" # Name of the y column in the input data. Default: "z"
gene = "feature_name" # Name of gene column in the input data. Default: "gene"
force_2d = false # Ignores z-column in the data if it is provided
min_molecules_per_gene = 1 # Minimal number of molecules per gene. Default: 1
exclude_genes = "APOE, SLC17A6, POU4F1, SYP, FABP7, MPZ, GLDN, SCN7A, DCN, PDGFRA, MGP, ALPL, CD74, PTPRC, IGFBP7, TINAGL1, SLC17A7, SLC17A8, INA, NEFH, CALCA, CALCB, NTRK1, NTRK2, NTRK3, PRDM12, RET, STUM, TRPM8, ENTPD3, CASQ2, SERPINA1, P2RY1, MRGPRX1, SCN11A, CDH1, OSMR, IL31RA, MRGPRX3, MRGPRX4, MRGPRD, GFRA2, SST, CCK, GFRA3, SCRG1, TRPV1, TRPA1, PTGER3, TAC1, ATP2B4, KIT, TMEM273, DOC2A, CHRNA7, CST3, CPNE4, S100A4, S100A16, PCP4, KCNV1, PCDH7, SFRP1, NEFL, REEP5, WLS, PVALB, ATF3, UCN, SEMA6A, ADCYAP1, PIEZO1, PIEZO2, GPR68, EHD3, SCN9A, SCN10A, OPRD1, OPRM1, OPRK1, CACNA2D1, CACNA2D2, PTGDR, HTR3A, CHRNA3, EDNRA, KCNG4, PLCB3, HRH1, NMB, SCG2, SCG3, NPPB, PTGIR, ADRA2C, AGT, KCND1, KCNA4, HRH2" # Comma-separated list of genes or regular expressions to ignore during segmentation. Example: 'Blank*,MALAT1'
min_molecules_per_cell = 100 # Minimal number of molecules for a cell to be considered as real. It's an important parameter, as it's used to infer several other parameters. Default: 3
min_molecules_per_segment = 25 # Minimal number of molecules in a segmented region, required for this region to be considered as a possible cell. Default: min-molecules-per-cell / 4
confidence_nn_id = 51 # Number of nearest neighbors to use for confidence estimation. Default: min-molecules-per-cell / 2 + 1

[segmentation]
scale = 10 # Negative values mean it must be estimated from `min_molecules_per_cell`
#scale = 50 # Negative values mean it must be estimated from `min_molecules_per_cell`
scale_std = "15%" # Standard deviation of scale across cells. Can be either number, which means absolute value of the std, or string ended with "%" to set it relative to scale. Default: "25%"
estimate_scale_from_centers = true # Use scale estimate from DAPI if provided. Default: true

n_clusters = 6 # Number of clusters to use for cell type segmentation. Default: 4
prior_segmentation_confidence = 0.0 # Confidence of the prior segmentation. Default: 0.2
iters = 500 # Number of iterations for the cell segmentation algorithm. Default: 500
n_cells_init = 0 # Initial number of cells

nuclei_genes = "" # Comma-separated list of nuclei-specific genes. If provided, `cyto-genes` has to be set, as well.
cyto_genes = "" # Comma-separated list of cytoplasm-specific genes. If provided, `nuclei-genes` has to be set, as well.

# The parameters below are not supposed to be changed normally
new_component_weight = 0.2 # Prior weight of assignment a molecule to new component. Default: 0.2
new_component_fraction = 0.3 # Fraction of distributions, sampled at each stage. Default: 0.3

[plotting]
gene_composition_neigborhood = 0 # Number of neighbors (i.e. 'k' in k-NN), which is used for gene composition visualization. Larger numbers leads to more global patterns. Default: estimate from min-molecules-per-cell
min_pixels_per_cell = 15 # Number of pixels per cell of minimal size, used to estimate size of the final plot. For most protocols values around 7-30 give enough visualization quality. Default: 15
